type Query {
    books: [Book]
    book(id: Int!): Book
    author(id: Int!): Author
}

type Mutation {
    updateBook(id: Int!, updateBookInput: UpdateBookInput!): Book
    removeBook(id: Int!): Book
}
